---
- name: Download WP-CLI
  get_url: url={{ wp_cli_url }} dest={{ wp_cli }} mode=0755
  tags: download

- name: Copy WP-CLI into container
  shell: docker cp {{ wp_cli }}  roundabout_wordpress_1:{{ wp_cli_bin }}
  tags: copy

- name: Active Wordpress theme spike
  shell: docker exec roundabout_wordpress_1 bash -c "cd {{ theme_root }} && {{ wp_cli_bin }} theme activate spike --allow-root "
  tags: activate_theme
