---
- name: Archive Round-About in local
  hosts: local
  roles:
    - { role: archive, tags: archive }


- name: Install Docker
  hosts: remote
  sudo: yes
  roles:
    - { role: docker, tags: docker }


- name: Deploy Round-About
  hosts: remote
  sudo: yes
  roles:
    - { role: deploy, tags: deploy }