---
- name: Checkout repository
  git:
    repo: https://github.com/twa-rs-demos/round-about.git
    dest: "{{ ra_path }}"
  tags: git

- name: Create docker-compose .env file
  template:
    src: env.j2
    dest: "{{ ra_path }}/.env"

- name: Archive round-about
  archive:
    path: "{{ ra_path }}"
    dest: "{{ ra_archive }}"
