---
- name: Install Docker
  shell: "curl -sSL https://get.docker.com/ | sh"
  become_method: sudo
  tags: install_docker

- name: Manage Docker as a non-root user
  shell: "usermod -aG docker $USER"
  become_method: sudo
  notify: Verify docker command without sudo

- name: Installing packages
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=present"
  with_items:
    - python-setuptools

- name: Installing dependencies for docker-compose
  easy_install:
    name: pip
    state: present

- name: Installing docker-compose
  pip:
    name: docker-compose
    state: present
