---
ra_dest: /home/ubuntu
ra_tar: round-about.tar.gz
wp_cli: /home/ubuntu/wp
wp_cli_bin: /usr/bin/wp
wp_cli_url: https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
theme_root: /var/www/html/wp-content/themes